apiVersion: apps/v1
kind: Deployment
metadata:
  name: imc-lamp8
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: imc-lamp8
  template:
    metadata:
      labels:
        app: imc-lamp8
    spec:
      containers:
      - name: imc-lamp8
        image: italomarcelo/php-apache
        ports:
        - containerPort: 80 # porta do serviço (targetport)