apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  selector:
    app: phpmyadmin

# se nodeport, utilize as linhas abaixo
  ports:
    - port: 8081
      targetPort: 80
      nodePort: 30001
  type: NodePort

# para loadbalancer, utilize as linhas abaixo
  # ports:
  # - protocol: TCP
  #   port: 8081
  #   targetPort: 80
  # type: LoadBalancer   